### ISSUE TITLE
build fail: Making all in gdk ... glib-mkenums [Errno 21] Is a directory

### ISSUE THREAD

**Issue by milkmiruku** [ayyi/samplecat#35]
```
...
make[5]: Leaving directory '/home/milk/pkgs/samplecat-git/src/samplecat/lib/waveform/sdl'
Making all in gtkglext-1.0
make[5]: Entering directory '/home/milk/pkgs/samplecat-git/src/samplecat/lib/waveform/gtkglext-1.0'
cd .. && /bin/sh ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-recursive
make[6]: Entering directory '/home/milk/pkgs/samplecat-git/src/samplecat/lib/waveform/gtkglext-1.0'
Making all in gdk
make[7]: Entering directory '/home/milk/pkgs/samplecat-git/src/samplecat/lib/waveform/gtkglext-1.0/gdk'
( cd . && glib-mkenums --template gtkglenumtypes.h.template \
gdkgl.h gdkgltokens.h gdkgltypes.h gdkglinit.h gdkglquery.h gdkglconfig.h gdkglcontext.h gdkgldrawable.h gdkglpixmap.h gdkglwindow.h gdkglx.h gdkglglext.h gdkglglxext.h /home/milk/pkgs/samplecat-git/src/samplecat/lib/waveform/gtkglext-1.0/gdk/ ) >> xgen-geth \
&& (cmp -s xgen-geth ./gdkglenumtypes.h || cp xgen-geth ./gdkglenumtypes.h ) \
&& rm -f xgen-geth
Traceback (most recent call last):
  File "/usr/bin/glib-mkenums", line 711, in <module>
    process_file(fname)
  File "/usr/bin/glib-mkenums", line 433, in process_file
    errors="replace_and_warn")
IsADirectoryError: [Errno 21] Is a directory: '/home/milk/pkgs/samplecat-git/src/samplecat/lib/waveform/gtkglext-1.0/gdk/'
make[7]: *** [Makefile:1070: gdkglenumtypes.h] Error 1
make[7]: Leaving directory '/home/milk/pkgs/samplecat-git/src/samplecat/lib/waveform/gtkglext-1.0/gdk'
make[6]: *** [Makefile:511: all-recursive] Error 1
make[6]: Leaving directory '/home/milk/pkgs/samplecat-git/src/samplecat/lib/waveform/gtkglext-1.0'
make[5]: *** [Makefile:418: all] Error 2
make[5]: Leaving directory '/home/milk/pkgs/samplecat-git/src/samplecat/lib/waveform/gtkglext-1.0'
make[4]: *** [Makefile:525: all-recursive] Error 1
make[4]: Leaving directory '/home/milk/pkgs/samplecat-git/src/samplecat/lib/waveform'
make[3]: *** [Makefile:434: all] Error 2
make[3]: Leaving directory '/home/milk/pkgs/samplecat-git/src/samplecat/lib/waveform'
make[2]: *** [Makefile:415: all-recursive] Error 1
make[2]: Leaving directory '/home/milk/pkgs/samplecat-git/src/samplecat/lib'
make[1]: *** [Makefile:540: all-recursive] Error 1
make[1]: Leaving directory '/home/milk/pkgs/samplecat-git/src/samplecat'
make: *** [Makefile:429: all] Error 2
==> ERROR: A failure occurred in build().
```

**Comment by milkmiruku** [comment]
This problem appears to have been resolved, thanks!

**Comment by ayyi** [comment]
Apologies for not updating the ticket. Thanks for reporting the issue. Much appreciated. Best regards
