### ISSUE TITLE
Colour drag targets wrong row

### ISSUE THREAD

**Issue by naught101** [ayyi/samplecat#6]
Doesn't seem to be segfaulting while adding tracks to the library now, but I get some really weird behaviour when trying to colour tracks - the colour isn't applied to the track I have selected, or to the one I drag the colour on to, but one further down. Also, I kept trying, and got a segfault

```
[ ... endless mp3 overreads ...]
[mp3 @ 0x7fffdc228fc0] overread, skip -5 enddists: -4 -4
[mp3 @ 0x7fffdc228fc0] overread, skip -5 enddists: -2 -2
[mp3 @ 0x7fffdc228fc0] overread, skip -7 enddists: -6 -6
error! wf_actor_paint: assertion 'actor' failed
[mp3 @ 0x7fffdc228fc0] overread, skip -5 enddists: -2 -2
[mp3 @ 0x7fffdc228fc0] overread, skip -7 enddists: -6 -6
[mp3 @ 0x7fffdc228fc0] overread, skip -5 enddists: -2 -2

Program received signal SIGSEGV, Segmentation fault.
0x0000000000498e42 in ?? ()
(gdb) bt
#0  0x0000000000498e42 in ?? ()
#1  0x0000000000498a85 in ?? ()
#2  0x0000000000498b1e in ?? ()
#3  0x00007ffff42133b8 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff4224d3d in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff422ca29 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff422d212 in g_signal_emit_by_name () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x000000000049a769 in ?? ()
#8  0x00007ffff3f44703 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff3f43ce5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff3f44048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff3f4430a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff55ff447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#13 0x0000000000428b6f in main ()
(gdb) 
```

**Comment by ayyi** [comment]
Commit 70d84e2801409c29432817a25f76d24a5121d783 is intended to fix the drag issue. Please re-open the issue if you see any futher problems.
Thanks!
